version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: syncmore
      MYSQL_USER: syncmore
      MYSQL_PASSWORD: 'syncmore'
      MYSQL_ROOT_PASSWORD: 'syncmore'
    ports:
      - "3306:3306"
