version: '3'

services:
  web:
    build: .
    command: uwsgi --http :8000 --module Syncmore.wsgi --workers 4 --threads 2
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: syncmore
      MYSQL_USER: syncmore
      MYSQL_PASSWORD: 'syncmore'
      MYSQL_ROOT_PASSWORD: 'syncmore'
    ports:
      - "3306:3306"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./path/to/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
