# Generated by Django 4.1.7 on 2023-09-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "First_Name",
                    models.CharField(max_length=30, verbose_name="First_Name"),
                ),
                (
                    "Last_Name",
                    models.CharField(max_length=30, verbose_name="Last_Name"),
                ),
                ("Username", models.CharField(max_length=30, verbose_name="Username")),
                ("password", models.CharField(max_length=32, verbose_name="password")),
                (
                    "address",
                    models.CharField(
                        default=None, max_length=255, verbose_name="address"
                    ),
                ),
                (
                    "phone",
                    models.IntegerField(default=0, max_length=15, verbose_name="phone"),
                ),
                (
                    "gender",
                    models.CharField(default=None, max_length=6, verbose_name="gender"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is_active"),
                ),
                (
                    "email",
                    models.CharField(default=None, max_length=30, verbose_name="email"),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created_time"
                    ),
                ),
            ],
        ),
    ]
