# Generated by Django 4.1.7 on 2023-12-07 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "First_Name",
                    models.CharField(
                        max_length=30, null=True, verbose_name="First_Name"
                    ),
                ),
                (
                    "Last_Name",
                    models.CharField(
                        max_length=30, null=True, verbose_name="Last_Name"
                    ),
                ),
                (
                    "Username",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Username"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "address",
                    models.CharField(
                        default="San Francisco",
                        max_length=255,
                        null=True,
                        verbose_name="address",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        default=None, max_length=6, null=True, verbose_name="gender"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, null=True, verbose_name="is_active"
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="created_time"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="updated_time"
                    ),
                ),
                (
                    "last_access_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="last_access_time"
                    ),
                ),
                (
                    "second_password",
                    models.IntegerField(null=True, verbose_name="second_password"),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Supervisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Zac Clark", max_length=50, verbose_name="name"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        default="Team Leader", max_length=50, verbose_name="position"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        default="zac@homemoreproject.org",
                        max_length=50,
                        null=True,
                        verbose_name="email",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, null=True, verbose_name="is_active"
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="created_time"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="updated_time"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.IntegerField(default=0, null=True, verbose_name="phone"),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="created_time"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, null=True, verbose_name="is_active"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="updated_time"
                    ),
                ),
                (
                    "phone_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="title")),
                ("content", models.TextField(verbose_name="content")),
                (
                    "created_time",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="created_time"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, null=True, verbose_name="is_active"
                    ),
                ),
                (
                    "updated_time",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="updated_time"
                    ),
                ),
                (
                    "note_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        default=None, max_length=30, null=True, verbose_name="email"
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="created_time"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, null=True, verbose_name="is_active"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="updated_time"
                    ),
                ),
                (
                    "email_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="title")),
                (
                    "document",
                    models.FileField(
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="",
                        verbose_name="document",
                    ),
                ),
                (
                    "created_time",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="created_time"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, null=True, verbose_name="is_active"
                    ),
                ),
                (
                    "updated_time",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="updated_time"
                    ),
                ),
                (
                    "issued_time",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="issued_time"
                    ),
                ),
                (
                    "expired_time",
                    models.DateField(null=True, verbose_name="expired_time"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Other", "Other"),
                            ("ID", "ID"),
                            ("Passport", "Passport"),
                            ("SSN", "SSN"),
                            ("Birth Certificate", "Birth Certificate"),
                            ("Housing", "Housing"),
                            ("Financial", "Financial"),
                            ("Insurance", "Insurance"),
                        ],
                        default="Other",
                        max_length=32,
                        null=True,
                        verbose_name="type",
                    ),
                ),
                (
                    "document_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="supervisor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supervisor",
                to="user.supervisor",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
