# Generated by Django 4.1.7 on 2023-09-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.IntegerField(default=0, verbose_name="phone"),
        ),
    ]
