# Generated by Django 4.1.7 on 2023-09-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(
                default="San Francisco", max_length=255, verbose_name="address"
            ),
        ),
    ]
