# Generated by Django 4.1.7 on 2023-10-20 16:21

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_document_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document",
            field=models.FileField(
                storage=storages.backends.s3.S3Storage(),
                upload_to="",
                verbose_name="document",
            ),
        ),
    ]
