# Generated by Django 4.1.7 on 2023-10-26 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_alter_supervisor_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supervisor",
            name="supervisor_user",
        ),
        migrations.AddField(
            model_name="user",
            name="user_supervisor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_supervisor",
                to="user.supervisor",
            ),
        ),
    ]
