# Generated by Django 4.1.7 on 2023-10-26 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_remove_supervisor_supervisor_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_supervisor",
        ),
        migrations.AddField(
            model_name="user",
            name="supervisor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.supervisor",
            ),
        ),
    ]
