# Generated by Django 4.1.7 on 2023-10-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_alter_user_supervisor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.AddField(
            model_name="document",
            name="expired_time",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="expired_time"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="is_active",
            field=models.BooleanField(
                default=True, null=True, verbose_name="is_active"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="issued_time",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="issued_time"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="type",
            field=models.CharField(
                default="ID", max_length=32, null=True, verbose_name="type"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="updated_time",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="updated_time"
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="is_active",
            field=models.BooleanField(
                default=True, null=True, verbose_name="is_active"
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="updated_time",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="updated_time"
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="is_active",
            field=models.BooleanField(
                default=True, null=True, verbose_name="is_active"
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="updated_time",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="updated_time"
            ),
        ),
        migrations.AddField(
            model_name="phone",
            name="is_active",
            field=models.BooleanField(
                default=True, null=True, verbose_name="is_active"
            ),
        ),
        migrations.AddField(
            model_name="phone",
            name="updated_time",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="updated_time"
            ),
        ),
        migrations.AddField(
            model_name="supervisor",
            name="is_active",
            field=models.BooleanField(
                default=True, null=True, verbose_name="is_active"
            ),
        ),
        migrations.AddField(
            model_name="supervisor",
            name="updated_time",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="updated_time"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_access_time",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="last_access_time"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_time",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="updated_time"
            ),
        ),
    ]
