# Generated by Django 4.1.7 on 2023-11-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0012_remove_user_email_remove_user_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="second_password",
            field=models.IntegerField(
                max_length=5, null=True, verbose_name="second_password"
            ),
        ),
    ]
