# Generated by Django 4.1.7 on 2023-11-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0013_user_second_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="second_password",
            field=models.IntegerField(null=True, verbose_name="second_password"),
        ),
    ]
