# Generated by Django 4.1.7 on 2023-11-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0015_alter_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.CharField(
                choices=[("ID", "ID"), ("Passport", "Passport")],
                default="ID",
                max_length=32,
                null=True,
                verbose_name="type",
            ),
        ),
    ]
