# Generated by Django 4.1.7 on 2023-12-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0016_alter_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="expired_time",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="expired_time"
            ),
        ),
    ]
