# Generated by Django 4.2.5 on 2023-12-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='expired_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expired_time'),
        ),
    ]
