# Generated by Django 4.2.5 on 2023-12-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_document_expired_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='expired_time',
            field=models.DateField(blank=True, null=True, verbose_name='expired_time'),
        ),
    ]
