# Generated by Django 4.1.7 on 2023-12-06 06:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0018_user_groups_user_is_superuser_user_last_login_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
    ]
