# Generated by Django 4.2.5 on 2023-12-06 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_user_groups_user_is_superuser_user_last_login_and_more'),
        ('user', '0019_alter_document_expired_time'),
    ]

    operations = [
    ]
