# Generated by Django 4.1.7 on 2023-12-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0020_user_groups_user_is_superuser_user_last_login_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
