# Generated by Django 4.2.5 on 2023-12-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_merge_20231205_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='expired_time',
            field=models.DateField(null=True, verbose_name='expired_time'),
        ),
    ]
