# Generated by Django 4.2.5 on 2023-12-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_document_expired_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='position',
            field=models.CharField(default='Team Leader', max_length=50, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='document',
            name='issued_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='issued_time'),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='updated_time'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='note',
            name='updated_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='updated_time'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='name',
            field=models.CharField(default='Zac Clark', max_length=50, verbose_name='name'),
        ),
    ]
