# Generated by Django 4.2.5 on 2023-12-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_supervisor_position_alter_document_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='First_Name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='First_Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Last_Name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Last_Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='San Francisco', max_length=255, null=True, verbose_name='address'),
        ),
    ]
