# Generated by Django 4.1.7 on 2023-12-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0022_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="issued_time",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="issued_time"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="updated_time",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="updated_time"
            ),
        ),
    ]
