# Generated by Django 4.2.5 on 2023-12-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='email',
            field=models.CharField(default='zac@homemoreproject.org', max_length=50, null=True, verbose_name='email'),
        ),
    ]
