# Generated by Django 4.1.7 on 2023-12-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        max_length=128, null=True, verbose_name="category"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="name")),
                (
                    "description",
                    models.CharField(
                        max_length=1024, null=True, verbose_name="description"
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=128, null=True, verbose_name="address"),
                ),
                (
                    "phone",
                    models.CharField(max_length=16, null=True, verbose_name="phone"),
                ),
                (
                    "email",
                    models.EmailField(max_length=30, null=True, verbose_name="email"),
                ),
                (
                    "website",
                    models.CharField(max_length=50, null=True, verbose_name="website"),
                ),
                (
                    "website_nickname",
                    models.CharField(
                        max_length=50, null=True, verbose_name="website_nickname"
                    ),
                ),
            ],
        ),
    ]
