# Generated by Django 4.1.7 on 2023-10-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="website_nickname",
            field=models.CharField(
                max_length=50, null=True, verbose_name="website_nickname"
            ),
        ),
    ]
